export const locations = [
  {
    slug: 'galapagar',
    name: 'Galapagar',
    title: 'Mago en Galapagar',
    description: 'Mago profesional en Galapagar especializado en magia de cerca para bodas, eventos corporativos y fiestas privadas en la sierra de Madrid.',
    keywords: 'mago galapagar, ilusionista galapagar, mago para comuniones galapagar, mago para bodas galapagar',
    zip: '28260',
    lat: '40.5786',
    lng: '-4.0011',
    neighborhoods: 'La Navata, Parquelagos, Colonia España',
  },
  {
    slug: 'las-rozas',
    name: 'Las Rozas',
    title: 'Mago en Las Rozas',
    description: 'Espectáculos de magia profesional en Las Rozas de Madrid. Ilusionismo exclusivo para eventos corporativos, bodas y fiestas VIP en la zona A-6.',
    keywords: 'mago las rozas, mago para empresas las rozas, mago de cerca las rozas, ilusionista las rozas',
    zip: '28231',
    lat: '40.4918',
    lng: '-3.8732',
    neighborhoods: 'Monte Rozas, Las Matas, El Cantizal, Európolis',
  },
  {
    slug: 'majadahonda',
    name: 'Majadahonda',
    title: 'Mago en Majadahonda',
    description: 'Servicios de magia e ilusionismo en Majadahonda. Mago de cerca para eventos exclusivos, bodas y presentaciones de empresa.',
    keywords: 'mago majadahonda, ilusionista majadahonda, mago para bodas majadahonda, mago de cerca majadahonda',
    zip: '28220',
    lat: '40.4735',
    lng: '-3.8722',
    neighborhoods: 'Monte del Pilar, El Plantío, Los Satélites',
  },
  {
    slug: 'pozuelo',
    name: 'Pozuelo de Alarcón',
    title: 'Mago en Pozuelo',
    description: 'Ilusionista de alto impacto en Pozuelo de Alarcón. Magia elegante para eventos privados, empresas y bodas en las zonas más exclusivas de Madrid.',
    keywords: 'mago pozuelo, mago pozuelo de alarcon, ilusionista pozuelo, mago para eventos pozuelo',
    zip: '28223',
    lat: '40.4375',
    lng: '-3.8158',
    neighborhoods: 'La Finca, Somosaguas, Prado de Somosaguas, Monteclaro',
  },
  {
    slug: 'boadilla',
    name: 'Boadilla del Monte',
    title: 'Mago en Boadilla',
    description: 'Mago profesional en Boadilla del Monte. Magia de cerca y mentalismo para bodas, eventos y celebraciones familiares exclusivas.',
    keywords: 'mago boadilla, mago boadilla del monte, ilusionista boadilla, mago para bodas boadilla',
    zip: '28660',
    lat: '40.4072',
    lng: '-3.8761',
    neighborhoods: 'Las Lomas, Valdecabañas, Viñas Viejas, El Pastel',
  },
  {
    slug: 'las-matas',
    name: 'Las Matas',
    title: 'Mago en Las Matas',
    description: 'Ilusionismo y magia de proximidad en Las Matas. El mago perfecto para tu evento privado o celebración familiar en Las Matas y cercanías.',
    keywords: 'mago las matas, ilusionista las matas, mago para eventos las matas, mago de cerca las matas',
    zip: '28290',
    lat: '40.5539',
    lng: '-3.8894',
    neighborhoods: 'Los Peñascales, Renfe Las Matas, Barrio de la Estación',
  }
];
